name: Deploy Sanity Studio
on:
  push:
      paths:
        - "sanity-studio/**"
  workflow_dispatch:
jobs:
  Deploy-Sanity-Studio:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sanity-studio
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: sanity-studio/yarn.lock
      - name: Installing Dependencies
        run: npx -p @sanity/cli sanity install
      - name: Publishing Studio
        run: npx -p @sanity/cli sanity deploy
